apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yax46k2qi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yax46k2qi-go 
  name: yax46k2qi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yax46k2qi-go 
